export default {
  field: [
    'pageName',
    'tabName',
    'placeholder1',
    'placeholder2',
    'placeholder3',
    'title1',
    'title2',
    'title3',
    'label1',
    'label2',
    'label3',
    'button1',
    'button2',
    'message1',
    'message2',
    'message3',
    'message4',
    'message5',
    'message6',
    'message7',
    'message8',
    'tip1',
    'tip2',
    'uploadTypeOptions.label1',
    'uploadTypeOptions.label2',
    'compareGroupOptions.label1',
    'compareGroupOptions.label2',
    'compareGroupOptions.label3',
    'compareTypeOptions.label1',
    'compareTypeOptions.label2',
    'compareTypeOptions.label3',
    'compareTypeOptions.label4',
    'compareTypeOptions.label5',
  ],
  value: {
    'en-US': [
      'Keyword Comparison',
      'Keyword Comparison Tool',
      'Enter keywords, one per line',
      'Enter keywords, one per line',
      'Enter keywords, one per line',
      'Selection Method',
      'Comparison Data',
      'Requirement Options',
      'Group 1',
      'Group 2',
      'Group 3',
      'Compare Now',
      'Export Comparison Results',
      'Failed to read file, please select again',
      'Only .csv format is supported',
      'File size cannot exceed 10MB',
      'Please enter requirement keywords',
      'Please select at least two groups to compare',
      'Please select requirement options',
      'Please select a file to upload',
      'No query results obtained',
      'Click to download sample file',
      'Supports .csv format, one keyword per line',
      'Manual Input',
      'File Upload',
      'Group 1',
      'Group 2',
      'Group 3',
      'Exact Match',
      'Completely Different',
      'Must Contain',
      'Cannot Contain',
      'Merge & Deduplicate',
    ],
    'zh-CN': [
      '关键词对比',
      '关键词对比工具',
      '请输入关键词，一行一个',
      '请输入关键词，一行一个',
      '请输入关键词，一行一个',
      '选择方式',
      '对比数据',
      '需求选项',
      '第一组',
      '第二组',
      '第三组',
      '立即对比',
      '导出对比结果',
      '文件读取失败，请重新选择',
      '只支持 .csv 格式的文件',
      '文件大小不能超过10MB',
      '请输入需求关键词',
      '请至少选择两组对比数据',
      '请选择需求选项',
      '请选择要上传的文件',
      '未获取到查询结果',
      '点击下载示例文件',
      '支持 .csv 格式文件，每行一个关键词',
      '手动录入',
      '文件上传',
      '第一组',
      '第二组',
      '第三组',
      '完全相同',
      '完全不同',
      '必须包含',
      '不能包含',
      '合并去重',
    ],
    'zh-TW': [

      '關鍵詞對比',
      '關鍵詞對比工具',
      '請輸入關鍵詞，一行一個',
      '請輸入關鍵詞，一行一個',
      '請輸入關鍵詞，一行一個',
      '選擇方式',
      '對比數據',
      '需求選項',
      '第一組',
      '第二組',
      '第三組',
      '立即對比',
      '導出對比結果',
      '文件读取失敗，請重新選擇',
      '只支持 .csv 格式的文件',
      '文件大小不能超過10MB',
      '請輸入需求關鍵詞',
      '請至少選擇兩組對比數據',
      '請選擇需求選項',
      '請選擇要上傳的文件',
      '未獲取到查詢結果',
      '點擊下載示例文件',
      '支持 .csv 格式文件，每行一個關鍵詞',
      '手動錄入',
      '文件上傳',
      '第一組',
      '第二組',
      '第三組',
      '完全相同',
      '完全不同',
      '必须包含',
      '不能包含',
      '合并去重',
    ],
  },
};

