export default {
  'pageName': 'IP/网站查询',
  'type1': 'IP/网站查询',
  'type2': 'IP/网站查询详情',
  'placeholder1': '请输入需要查询的域名或IP地址，一行一个，单次最多提交20个',
  'button1': '立即查询',
  'button2': '导出查询列表',
  'button3': 'VIP查询通道',
  'button4': '详情',
  'button5': '导出',
  'button6': '返回列表页',
  'button7': '导出站点信息',
  'button8': '查询站点权重',
  'message1': '请输入需要查询的域名或IP地址！',
  'message2': '请选择需要导出的数据',
  'message3': '请选择需要查询的域名！',
  'introduce1': '工具介绍：',
  'content1': '1、Kobetools IP/网站查询工具支持批量查询域名的IP地址和同IP网站信息。',
  'content2': '2、Kobetools IP/网站查询工具可以帮助分析服务器上的网站数量和质量。',
  'columns.label1': '序号',
  'columns.label2': '域名信息',
  'columns.label3': 'IP地址',
  'columns.label4': 'IP地区',
  'columns.label5': '站点个数',
  'columns.label6': '查询时间',
  'columns.label7': '操作',
  'detailColumns.label1': '序号',
  'detailColumns.label2': '域名信息',
  'detailColumns.label3': '百度PC权重',
  'detailColumns.label4': '百度移动权重',
  'detailColumns.label5': '搜狗PC权重',
  'detailColumns.label6': '搜狗移动权重',
  'detailColumns.label7': '神马权重',
  'detailColumns.label8': '必应权重',
  'detailColumns.label9': '首页标题',
};

