export default {
  'pageName': '外链查询',
  'type1': '外链查询',
  'type2': '外链查询详情',
  'placeholder1': '请输入需要查询的域名，一行一个，单次最多提交20个，格式如：google.com',
  'button1': '立即查询',
  'button2': '导出查询列表',
  'button3': 'VIP查询通道',
  'button4': '详情',
  'button5': '导出',
  'button6': '返回列表页',
  'button7': '导出站点信息',
  'button8': '查询站点权重',
  'message1': '请输入需要查询的域名！',
  'message2': '请选择需要查询的域名！',
  'introduce1': '工具介绍：',
  'content1': '1、Kobetools外链查询工具支持批量查询网站的外链数据。',
  'content2': '2、Kobetools外链查询工具可以帮助分析网站的外链质量和分布情况。',
  'columns.label1': '序号',
  'columns.label2': '域名信息',
  'columns.label3': '反链数量',
  'columns.label4': '有回链',
  'columns.label5': '高权重数',
  'columns.label6': '最高权重',
  'columns.label7': '发现时间',
  'columns.label8': '操作',
  'detailColumns.label1': '序号',
  'detailColumns.label2': '域名',
  'detailColumns.label3': '移动权重',
  'detailColumns.label4': '反链数',
  'detailColumns.label5': '链接名称',
  'detailColumns.label6': '链接地址',
  'detailColumns.label7': '是否回链',
  'detailColumns.label8': '发现时间',
};

