export default {
  field: [
    'pageName',
    'type1',
    'placeholder1',
    'placeholder2',
    'button1',
    'button2',
    'button3',
    'message1',
    'label1',
    'label2',
    'introduce1',
    'content1',
    'content2',
    'columns.label1',
    'columns.label2',
    'columns.label3',
    'columns.label4',
    'columns.label5',
    'columns.label6',
    'columns.label7',
    'searchEngines.baidu',
    'searchEngines.google',
    'searchEngines.bing',
    'searchEngines.so',
    'searchEngines.sogou',
    'searchEngines.sm',
    'searchEngines.toutiao',
    'searchEngines.yahu',
    'searchEngines.yandex',
  ],
  value: {
    'en-US': [
      'Keywords Index Query',
      'Keywords Index Query',
      'Enter site domain, e.g.: www.google.com',
      'Enter domains to query, one per line, max 10 per submission, format: google.com',
      'Query Now',
      'Export to Local',
      'VIP Query Channel',
      'Please enter domain information!',
      'Site Domain',
      'Search Engine',
      'Tool Introduction:',
      '1. Kobetools keyword index query tool supports efficient, large-scale querying of keyword index status for site optimization, used to analyze keyword density and relevance within the site.',
      '2. Sites without keyword index cannot optimize corresponding keyword rankings, need to check keyword density and relevance layout within the site, and the inclusion status of corresponding related content.',
      'No.',
      'Website Domain',
      'Keyword',
      'Search Engine',
      'Search Status',
      'Query Time',
      'Action',
      'Baidu',
      'Google',
      'Bing',
      '360',
      'Sogou',
      'Shenma',
      'Toutiao',
      'Yahoo',
      'Yandex',
    ],
    'zh-CN': [
      '关键词索引查询',
      '关键词索引查询',
      '请输入站点域名，如：www.google.com',
      '请输入需要查询的域名信息，一行一个，单次最多提交10个，格式如：google.com',
      '立即查询',
      '导出到本地',
      'VIP查询通道',
      '请输入需要查询的域名信息！',
      '站点域名',
      '搜索引擎',
      '工具介绍：',
      '1、Kobetools关键词索引査询工具支持高效率、大批量査询站点优化的关键词的索引状态，用于分析站内关键词的密度和相关性。',
      '2、没有关键词索引的站点，无法优化对应关键词的排名，需要检査关键词在站内的密度和相关性布局，以及对应相关内容的收录情况。',
      '序号',
      '网站域名',
      '关键词',
      '搜索引擎',
      '搜索状态',
      '查询时间',
      '操作',
      '百度',
      '谷歌',
      '必应',
      '360',
      '搜狗',
      '神马',
      '头条',
      '雅虎',
      'Yandex',
    ],
    'zh-TW': [
      '關鍵詞索引查詢',
      '關鍵詞索引查詢',
      '請輸入站點域名，如：www.google.com',
      '請輸入需要查詢的域名信息，一行一個，單次最多提交10個，格式如：google.com',
      '立即查詢',
      '導出到本地',
      'VIP查詢通道',
      '請輸入需要查詢的域名信息！',
      '站點域名',
      '搜索引擎',
      '工具介紹：',
      '1、Kobetools關鍵詞索引査詢工具支持高效率、大批量査詢站點優化的關鍵詞的索引狀態，用於分析站內關鍵詞的密度和相關性。',
      '2、沒有關鍵詞索引的站點，無法優化對應關鍵詞的排名，需要檢査關鍵詞在站內的密度和相關性布局，以及對應相關內容的收錄情況。',
      '序號',
      '網站域名',
      '關鍵詞',
      '搜索引擎',
      '搜索狀態',
      '查詢時間',
      '操作',
      '百度',
      '谷歌',
      '必應',
      '360',
      '搜狗',
      '神馬',
      '頭條',
      '雅虎',
      'Yandex',
    ],
  },
};

