export default {
  field: [
    'pageName',
    'type1',
    'type2',
    'type3',
    'placeholder1',
    'placeholder2',
    'placeholder3',
    'button1',
    'button2',
    'button3',
    'button4',
    'button5',
    'button6',
    'button7',
    'message1',
    'message2',
    'message3',
    'message4',
    'title1',
    'title2',
    'introduce1',
    'content1',
    'content2',
    'content3',
    'content4',
    'table.text1',
    'table.text2',
    'table.text3',
    'table.text4',
    'table.text5',
    'domainColumns.label1',
    'domainColumns.label2',
    'domainColumns.label3',
    'domainColumns.label4',
    'domainColumns.label5',
    'domainColumns.label6',
    'domainColumns.label7',
    'domainColumns.label8',
    'enterColumns.label1',
    'enterColumns.label2',
    'enterColumns.label3',
    'enterColumns.label4',
    'enterColumns.label5',
    'enterColumns.label6',
    'enterColumns.label7',
    'enterColumns.label8',
    'recordColumns.label1',
    'recordColumns.label2',
    'recordColumns.label3',
    'recordColumns.label4',
    'recordColumns.label5',
    'recordColumns.label6',
    'recordColumns.label7',
    'recordColumns.label8',
  ],
  value: {
    'en-US': [
      'ICP Record Query',
      'ICP Record Query',
      'Enterprise/Personal ICP Query',
      'Domain ICP History Query',
      'Enter domains to query, one per line, max 20 per submission, format: google.com',
      'Enter enterprise/personal full name, one per line, max 20 per submission, e.g.: Huawei Technologies Co., Ltd.',
      'Enter domains to query, one per line, max 20 per submission, format: google.com',
      'Query Now',
      'Export Query Results',
      'Export Registered Domains',
      'Export Unregistered Domains',
      'VIP Query Channel',
      'Back to Query Page',
      'Upgrade VIP',
      'Please enter domains to query!',
      'Please enter enterprise/personal full name!',
      'No query results obtained',
      'Clicked upgrade VIP',
      'Export File',
      'Warm Reminder',
      'Tool Introduction:',
      '1. Kobetools domain ICP record query tool supports efficient, batch querying of domain ICP record information.',
      '2. Kobetools enterprise/personal ICP query can batch query all domain ICP record information under an enterprise based on the record subject.',
      '3. Kobetools domain ICP history query tool supports efficient, batch querying of domain historical ICP record information.',
      'Your current daily query limit is 100, currently used 88. More query quota can be obtained by upgrading VIP membership.',
      'No Data',
      'Total: ',
      ' items',
      'Success: ',
      'Failed: ',
      'No.',
      'Domain',
      'Record Subject',
      'Entity Type',
      'Main Record No.',
      'Record No.',
      'Record ID',
      'Review Time',
      'No.',
      'Domain Owner',
      'Domain',
      'Entity Type',
      'Main Record No.',
      'Record No.',
      'Record ID',
      'Review Time',
      'No.',
      'Domain',
      'Domain Owner',
      'Entity Type',
      'Main Record No.',
      'Record No.',
      'Record ID',
      'Review Time',
    ],
    'zh-CN': [
      '备案信息查询',
      '备案信息查询',
      '企业/个人备案查询',
      '域名备案历史查询',
      '请输入需要查询的域名，一行一个，单次最多提交20个，格式如：google.com',
      '请输入需要查询的企业全称或个人全称，一行一个，单次最多提交20个，格式如：华为技术有限公司',
      '请输入需要查询的域名，一行一个，单次最多提交20个，格式如：google.com',
      '立即查询',
      '导出查询结果',
      '导出备案域名',
      '导出未备案域名',
      'VIP查询通道',
      '返回查询页面',
      '升级VIP权限',
      '请输入需要查询的域名！',
      '请输入需要查询的企业全称或个人全称！',
      '未获取到查询结果',
      '已点击升级VIP权限',
      '导出文件',
      '温馨提示',
      '工具介绍：',
      '1、Kobetools域名备案查询工具支持高效率、批量、查询域名ICP备案信息。',
      '2、Kobetools企业/个人ICP备案查询，可根据备案主体批量查询该企业下所有域名的ICP备案信息。',
      '3、Kobetools域名备案历史查询工具支持高效率、批量、查询域名历史ICP备案信息。',
      '您当前日查询额度上限为100个，当前已使用88，更多查询额度可通过升级VIP权限获取。',
      '暂无数据',
      '页面共计：',
      '条',
      '成功：',
      '失败：',
      '序号',
      '域名信息',
      '备案主体',
      '单位性质',
      '主备案号',
      '备案号',
      '备案ID',
      '审核时间',
      '序号',
      '域名所有人',
      '域名信息',
      '单位性质',
      '主备案号',
      '备案号',
      '备案ID',
      '审核时间',
      '序号',
      '域名信息',
      '域名所有人',
      '单位性质',
      '主备案号',
      '备案号',
      '备案ID',
      '审核时间',
    ],
    'zh-TW': [
      '備案信息查詢',
      '備案信息查詢',
      '企業/個人備案查詢',
      '域名備案歷史查詢',
      '請輸入需要查詢的域名，一行一個，單次最多提交20個，格式如：google.com',
      '請輸入需要查詢的企業全稱或個人全稱，一行一個，單次最多提交20個，格式如：華為技術有限公司',
      '請輸入需要查詢的域名，一行一個，單次最多提交20個，格式如：google.com',
      '立即查詢',
      '導出查詢結果',
      '導出備案域名',
      '導出未備案域名',
      'VIP查詢通道',
      '返回查詢頁面',
      '升級VIP權限',
      '請輸入需要查詢的域名！',
      '請輸入需要查詢的企業全稱或個人全稱！',
      '未獲取到查詢結果',
      '已點擊升級VIP權限',
      '導出文件',
      '溫馨提示',
      '工具介紹：',
      '1、Kobetools域名備案查詢工具支持高效率、批量、查詢域名ICP備案信息。',
      '2、Kobetools企業/個人ICP備案查詢，可根據備案主體批量查詢該企業下所有域名的ICP備案信息。',
      '3、Kobetools域名備案歷史查詢工具支持高效率、批量、查詢域名歷史ICP備案信息。',
      '您當前日查詢額度上限為100個，當前已使用88，更多查詢額度可通過升級VIP權限獲取。',
      '暫無數據',
      '頁面共計：',
      '條',
      '成功：',
      '失敗：',
      '序號',
      '域名信息',
      '備案主體',
      '單位性質',
      '主備案號',
      '備案號',
      '備案ID',
      '審核時間',
      '序號',
      '域名所有人',
      '域名信息',
      '單位性質',
      '主備案號',
      '備案號',
      '備案ID',
      '審核時間',
      '序號',
      '域名信息',
      '域名所有人',
      '單位性質',
      '主備案號',
      '備案號',
      '備案ID',
      '審核時間',
    ],
  },
};

