export default {
  'placeholder1': '输入敏感违禁词',
  'placeholder2': '选择违禁词库组',
  'btn1': '搜索',
  'btn2': '导出.txt文本压缩包',
  'btn3': '导出Excel表格',
  'btn4': '重置',
  'btn5': '刷新',
  'btn6': '删除',
  'btn7': '保存',
  'message1': '是否删除？',
  'message2': '您暂未修改数据',
  'message3': '保存成功',
  'message4': '删除成功',
  'sensitiveTableColumns.title1': 'ID',
  'sensitiveTableColumns.title2': '敏感违禁词',
  'sensitiveTableColumns.title3': '所属词库分组',
  'sensitiveTableColumns.title4': '更新时间',
  'sensitiveTableColumns.title5': '操作',
};
