export default {
  'pageName': '网站降权查询',
  'type1': '网站降权查询',
  'placeholder1': '请输入需要查询的网站域名，一行一个，单词最多提交10个，格式如：www.google.com',
  'button1': '立即查询',
  'button2': '导出正常站点',
  'button3': '导出降权站点',
  'button4': 'VIP查询通道',
  'message1': '请选择搜索引擎！',
  'message2': '请输入需要查询的网站域名！',
  'label1': '搜索引擎',
  'introduce1': '工具介绍：',
  'content1': '1、Kobetools网站收录查询工具支持高效率、大批量查询网站在各个搜索引擎的收录数据。',
  'content2': '2、Kobetools网站收录查询工具还支持百度、谷歌搜索引擎的详细收录数据查询，如总收录，日收录，周收录，月收录等。',
  'columns.label1': '序号',
  'columns.label2': '网站域名',
  'columns.label3': '操作',
  'searchEngines.baidu': '百度',
  'searchEngines.google': '谷歌',
  'searchEngines.bing': '必应',
  'searchEngines.so': '360',
  'searchEngines.sogou': '搜狗',
  'searchEngines.sm': '神马',
  'searchEngines.toutiao': '头条',
  'searchEngines.yahu': '雅虎',
  'searchEngines.yandex': 'Yandex',
};

