export default {
  field: [
    'pageName',
    'type1',
    'placeholder1',
    'button1',
    'button2',
    'button5',
    'message1',
    'message2',
    'message3',
    'title1',
    'introduce1',
    'content1',
    'filter.label1',
    'filter.label2',
    'filter.label3',
    'filter.label4',
    'filter.label5',
    'filter.label6',
    'filter.label7',
    'filter.label8',
    'filter.label9',
    'filter.label10',
    'filter.label11',
    'filter.label12',
    'securityColumns.label1',
    'securityColumns.label2',
    'securityColumns.label3',
    'securityColumns.label4',
    'securityColumns.label5',
    'securityColumns.label6',
    'securityColumns.label7',
    'securityColumns.label8',
    'securityColumns.label9',
    'securityColumns.label10',
    'securityColumns.label11',
    'securityColumns.label12',
    'status.risk',
    'status.blacklist',
  ],
  value: {
    'en-US': [
      'Domain Security Query',
      'Domain Security Query',
      'Enter domains to query, one per line, max 20 per submission, format: google.com',
      'Query Now',
      'Export Query Results',
      'VIP Query Channel',
      'No query results obtained',
      'Please select query items!',
      'Please enter domain information!',
      'Query Items',
      'Tool Introduction:',
      '1. Kobetools domain security query tool can efficiently query in bulk whether websites are blocked, intercepted by WeChat, Baidu, QQ, etc.',
      'Is Blocked',
      'WeChat Security',
      'QQ Security',
      'Mobile DNS Pollution',
      'ICP Security',
      'Baidu Intercept',
      'Google Intercept',
      '360 Intercept',
      'Sogou Intercept',
      'Toutiao Intercept',
      'Douyin Intercept',
      'Microsoft Edge Intercept',
      'No.',
      'Domain',
      'Is Blocked',
      'QQ Security',
      'WeChat Security',
      'Baidu Intercept',
      'ICP Security',
      'Google Intercept',
      '360 Intercept',
      'Sogou Intercept',
      'Toutiao Intercept',
      'Douyin Intercept',
      'Risk Website',
      'Blacklist',
    ],
    'zh-CN': [
      '域名安全查询',
      '域名安全查询',
      '请输入需要查询的域名，一行一个，单次最多提交20个，格式如：google.com',
      '立即查询',
      '导出查询结果',
      'VIP查询通道',
      '未获取到查询结果',
      '请选择查询项！',
      '请输入需要查询的域名信息！',
      '查询项',
      '工具介绍：',
      '1、Kobetools域名安全查询工具可以大批量、高效率查询网站是否被墙、是否被微信、百度、QQ拦截等风险。',
      '是否被墙',
      '微信安全',
      'QQ安全',
      '移动DNS污染',
      '备案安全',
      '百度拦截',
      '谷歌拦截',
      '360拦截',
      '搜狗拦截',
      '头条拦截',
      '抖音拦截',
      '微软Edge拦截',
      '序号',
      '域名信息',
      '是否被墙',
      'QQ安全',
      '微信安全',
      '百度拦截',
      '备案安全',
      '谷歌拦截',
      '360拦截',
      '搜狗拦截',
      '头条拦截',
      '抖音拦截',
      '风险网站',
      '黑名单',
    ],
    'zh-TW': [
      '域名安全查詢',
      '域名安全查詢',
      '請輸入需要查詢的域名，一行一個，單次最多提交20個，格式如：google.com',
      '立即查詢',
      '導出查詢結果',
      'VIP查詢通道',
      '未獲取到查詢結果',
      '請選擇查詢項！',
      '請輸入需要查詢的域名信息！',
      '查詢項',
      '工具介紹：',
      '1、Kobetools域名安全查詢工具可以大批量、高效率查詢網站是否被牆、是否被微信、百度、QQ攔截等風險。',
      '是否被牆',
      '微信安全',
      'QQ安全',
      '移動DNS汙染',
      '備案安全',
      '百度攔截',
      '谷歌攔截',
      '360攔截',
      '搜狗攔截',
      '頭條攔截',
      '抖音攔截',
      '微軟Edge攔截',
      '序號',
      '域名信息',
      '是否被牆',
      'QQ安全',
      '微信安全',
      '百度攔截',
      '備案安全',
      '谷歌攔截',
      '360攔截',
      '搜狗攔截',
      '頭條攔截',
      '抖音攔截',
      '風險網站',
      '黑名單',
    ],
  },
};

