export default {
  field: [
    'pageName',
    'tab1',
    'tab2',
    'tab3',
    'tab4',
    'tab5',
    'tab6',
    'tab7',
    'tab8',
    'tab9',
    'type1',
    'type2',
    'title1',
    'title2',
    'title3',
    'title4',
    'title5',
    'title6',
    'title7',
    'label1',
    'label2',
    'label3',
    'label4',
    'label5',
    'label6',
    'label7',
    'label8',
    'label9',
    'placeholder1',
    'placeholder2',
    'placeholder3',
    'placeholder4',
    'placeholder5',
    'placeholder6',
    'placeholder7',
    'placeholder8',
    'placeholder9',
    'placeholder10',
    'placeholder11',
    'placeholder12',
    'placeholder13',
    'placeholder14',
    'message1',
    'message2',
    'message3',
    'message4',
    'message5',
    'message6',
    'message7',
    'message8',
    'message9',
    'message10',
    'message11',
    'message12',
    'message13',
    'message14',
    'message15',
    'message16',
    'message17',
    'button1',
    'button2',
    'button3',
    'button4',
    'button5',
    'button6',
    'button7',
    'button8',
    'button9',
    'button10',
    'button11',
    'introduce1',
    'introduce2',
    'content1',
    'content2',
    'content3',
    'content4',
    'content5',
    'content6',
    'content7',
    'content8',
    'content9',
    'content10',
    'aiPromptTitle',
    'outputLanguage',
    'miningSource',
    'miningCount',
    'searchEngine',
    'zzPlatform',
    'monthSearch',
    'searchIndex',
    'diffLevel',
    'fissionCount',
    'sortOrder',
    'filterCondition',
    'titleLength',
    'areaA',
    'areaB',
    'areaC',
    'areaD',
    'cPrefix',
    'cCenter',
    'cSuffix',
    'comboItem',
    'comboResult',
    'tab9_1',
    'tab9_2',
    'promptDefault',
    'example.num',
    'example.word1',
    'example.word2',
    'example.word3',
    'example.word4',
    'example.word5',
    'example.btnConfig',
    'includeOptions.label1',
    'includeOptions.label2',
    'excludeOptions.label1',
    'excludeOptions.label2',
    'depthOptions.label1',
    'depthOptions.label2',
    'depthOptions.label3',
    'depthOptions.label4',
    'depthOptions.label5',
    'keyOptions.label1',
    'keyOptions.label2',
    'sensitiveOptions.label1',
    'sensitiveOptions.label2',
    'customOptions.label0',
    'customOptions.label1',
    'customOptions.label2',
    'customOptions.label3',
    'supportOptions.label1',
    'supportOptions.label2',
    'supportOptions.label3',
    'supportOptions.label4',
    'supportOptions.label5',
    'supportOptions.label6',
    'xgssSupportOptions.label1',
    'xgssSupportOptions.label2',
    'xgssSupportOptions.label3',
    'xgssSupportOptions.label4',
    'xgssSupportOptions.label5',
    'xgssSupportOptions.label6',
    'xgssSupportOptions.label7',
    'xgssSupportOptions.label8',
    'xgssSupportOptions.label9',
    'ZZSourceOptions.label1',
    'ZZSourceOptions.label2',
    'ZZPlatformOptions1.label1',
    'ZZPlatformOptions1.label2',
    'ZZPlatformOptions2.label1',
    'ZZPlatformOptions2.label2',
    'sourceOptions.label1',
    'sourceOptions.label2',
    'sourceOptions.label3',
    'engineOptions.label1',
    'engineOptions.label2',
    'engineOptions.label3',
    'engineOptions.label4',
    'engineOptions.label5',
    'engineOptions.label6',
    'GLEngineOptions.label1',
    'GLEngineOptions.label2',
    'GLEngineOptions.label3',
    'GLEngineOptions.label4',
    'GLEngineOptions.label5',
    'GLEngineOptions.label6',
    'GLEngineOptions.label7',
    'GLEngineOptions.label8',
    'typeOptions.label0',
    'typeOptions.label-1',
    'typeOptions.label1',
    'typeOptions.label2',
    'typeOptions.label3',
    'typeOptions.label4',
    'typeOptions.label5',
    'typeOptions.label6',
    'typeOptions.label7',
    'typeOptions.label8',
    'weightOptions.label0',
    'weightOptions.label1',
    'weightOptions.label2',
    'weightOptions.label3',
    'addTypeOptions.label1',
    'addTypeOptions.label2',
    'orderOptions.label1',
    'orderOptions.label2',
    'orderOptions.label3',
    'orderOptions.label4',
    'orderOptions.label5',
    'orderOptions.label6',
    'orderOptions.label7',
    'orderOptions.label8',
    'lengthOptions.unlimited',
    'LBDepthOptions.label1',
    'LBDepthOptions.label2',
    'LBDepthOptions.label3',
    'LBDepthOptions.label4',
    'LBOrderOptions.label1',
    'LBOrderOptions.label2',
    'LBOrderOptions.label3',
    'AILangOptions.label1',
    'AILangOptions.label2',
    'AILangOptions.label3',
    'AILangOptions.label4',
    'AILangOptions.label5',
    'AILangOptions.label6',
    'AILangOptions.label7',
    'AILangOptions.label8',
    'AILangOptions.label9',
    'AILangOptions.label10',
    'AILangOptions.label11',
    'AILangOptions.label12',
    'AILangOptions.label13',
    'AILangOptions.label14',
    'AILangOptions.label15',
    'AILangOptions.label16',
    'AILangOptions.label17',
    'AILangOptions.label18',
    'AILangOptions.label19',
    'AILangOptions.label20',
    'AILangOptions.label21',
    'AILangOptions.label22',
    'AILangOptions.label23',
    'AILangOptions.label24',
    'AILangOptions.label25',
    'AILangOptions.label26',
    'AILangOptions.label27',
    'AILangOptions.label28',
    'AILangOptions.label29',
    'AILangOptions.label30',
    'taskTableColumns.title1',
    'taskTableColumns.title2',
    'taskTableColumns.title3',
    'taskTableColumns.title4',
    'taskTableColumns.title5',
    'taskTableColumns.title6',
    'taskTableColumns.title7',
    'myTableColumns.title1',
    'myTableColumns.title2',
    'myTableColumns.title3',
    'myTableColumns.title4',
    'myTableColumns.title5',
  ],
  value: {
    'en-US': [
      'Keyword Mining',
      'Drop-down Keywords',
      'Combination Keywords',
      'Related Search',
      'Trending Search',
      'Competitor Keywords',
      'Keyword Planner',
      'AI Mining',
      'Webmaster Keywords',
      'Keyword Fission',
      'Keyword Mining',
      'Keyword Combination',
      'Mining Platform',
      'Mining Depth',
      'Advanced Filtering',
      'Include/Exclude',
      'Combination Method',
      'Smart Spacing',
      'Select All/None',
      'Keyword Deduplication',
      'Special Character Filtering',
      'Preserve Original Words',
      'Sensitive Word Filtering',
      'Character Length',
      'Minimum',
      'Maximum',
      'Results Include',
      'Results Exclude',
      'Please enter the keywords to be mined, one keyword per line',
      'Please select custom word library',
      'Please select minimum character count',
      'Please select maximum character count',
      'Please enter keywords, one per line',
      'Please enter competitor URL',
      'Please select keyword generation language',
      'Please enter AI prompt',
      'One per line, please enter combination items',
      'Please enter keywords, one per line',
      'Please enter competitor official URL, e.g.: https://www.google.com, one per line, max 5 websites',
      'Please enter competitor URL links for keyword extraction, one URL per line, must include https or http',
      'Please enter Simplified Chinese keywords, one per line',
      'Please enter product or service names for keyword mining, one per line, e.g.: SEO Company',
      'Please select a mining platform',
      'Please select mining depth',
      'Please enter keywords',
      'All keywords have been filtered',
      'Task created successfully',
      'Please enter keywords C',
      'Please select a combination method',
      'Combination successful',
      'Please combine keywords first',
      'Copy successful',
      'Copy failed',
      'Please select mining source',
      'Please select search engine',
      'Please select webmaster platform',
      'AI prompt must contain only {keyword}, {number}, {language} wildcards',
      'Please select output language',
      'Please select sort order',
      'Submit',
      'Combine Keywords',
      'Insert Combination',
      'Clear Combinations',
      'Mine Keywords',
      'Generate AI Keywords',
      'Insert AI Prompt',
      'Start Mining',
      '1. Split Keywords',
      '2. Extract All Roots',
      '3. Generate Synonyms',
      'Feature Introduction',
      'Usage Instructions',
      'Drop-down keywords, also known as suggestion words or search box keywords, are the related words that appear based on what you type in the search box.',
      'If all results are filtered by sensitive words or length filters, it is recommended to modify the configuration before mining.',
      'Kobetools Keyword Combination tool is a highly efficient multi-language text combination tool that supports large-scale combinations in seconds. It can flexibly set combination rules and filtering conditions to generate the keywords you need.',
      'When using the keyword combination tool, the core keyword must be placed in Area C. Each keyword must be entered on a new line. The combined keywords support online cloud storage and local TXT/Excel download.',
      'Related search tool can mine related search keywords from search engines like Baidu and Google, helping you discover more potential long-tail keywords and user search intent.',
      'Trending search tool can mine hot search keywords from search engines, helping you quickly understand hot topics and user search habits.',
      'AI keyword generation tool combines AI big data models to automatically generate keywords for you, based on market research, user search behavior analysis and other factors.',
      'Support custom AI prompts, you can flexibly adjust the generation strategy according to your needs, providing strong support for your SEO optimization and advertising.',
      'Please enter keywords and set fission conditions',
      'Support include/exclude/length/sensitive word filtering',
      'AI Prompt',
      'Output Language',
      'Mining Source',
      'Mining Count',
      'Search Engine',
      'Webmaster Platform',
      'Monthly Search Volume',
      'Search Index',
      'Difficulty Level',
      'Fission Count',
      'Sort Order',
      'Filter Condition',
      'Title Character Length',
      'A',
      'B',
      'C',
      'D',
      'Prefix',
      'Center',
      'Suffix',
      'Combination Item',
      'Combination Result',
      'Semantic Fission',
      'Synonym Fission',
      'Please help me find {number} keywords related to {keyword}. The keywords should meet commercial search needs, have certain search popularity, and be as concise as possible. Keyword directions can be combined from price, manufacturer, ranking, recommendations, cost, wholesale, popular regions, categories, usage scenarios, etc. Just output the keywords, one per line, without any other text information. Output in {language}',
      'items',
      'Google',
      'SEO',
      'optimization',
      'for',
      'tips',
      'Fission Config',
      'Any one',
      'All',
      'Any one',
      'All',
      'Layer 1',
      'Layer 2',
      'Layer 3',
      'Layer 4',
      'Layer 5',
      'Remove Punctuation',
      'Remove Spaces',
      'Public Library',
      'Custom Library',
      'Public Library',
      'Political',
      'Common Library',
      'Common Filter',
      'Baidu',
      'Google',
      'Bing',
      'Toutiao',
      'Sogou',
      '360',
      'Baidu',
      'Google',
      'Bing',
      'Toutiao',
      '360',
      'Shenma',
      'Sogou',
      'Douyin',
      'Xiaohongshu',
      'Baidu',
      'Google',
      'Aizhan Tools',
      'Webmaster Tools',
      'SEMrush',
      'Ahrefs',
      'Webmaster Platform Keywords',
      'Bidding Keywords',
      'Site SEO Settings',
      'Baidu',
      'Google',
      'Bing',
      'Shenma',
      'Sogou',
      '360',
      'Invalid Keywords',
      'Brand Keywords',
      'Contact Keywords',
      'Prohibited Words',
      'Knowledge Keywords',
      'Question Keywords',
      'Media Keywords',
      'Low Value Keywords',
      'Manual Input',
      'Smart Cleaning',
      'Drop-down Keywords',
      'Combination Keywords',
      'Related Search',
      'Trending Search',
      'Competitor Keywords',
      'Keyword Planner',
      'AI Mining',
      'Webmaster Keywords',
      'Original',
      'Weight 1',
      'Weight 2',
      'Weight 3',
      'New Task',
      'Existing Task',
      'C (Suffix)',
      'AC',
      'BC',
      'CD',
      'BCD',
      'ABC',
      'ACD',
      'ABCD',
      'Unlimited',
      '2 items',
      '3 items',
      '4 items',
      '5 items',
      'Default Order',
      'Length Sort',
      'Random Order',
      'Simplified Chinese',
      'English',
      'Traditional Chinese',
      'Russian',
      'Japanese',
      'French',
      'German',
      'Portuguese',
      'Arabic',
      'Spanish',
      'Italian',
      'Vietnamese',
      'Korean',
      'Hindi',
      'Bengali',
      'Indonesian',
      'Turkish',
      'Thai',
      'Telugu',
      'Tamil',
      'Malay',
      'Czech',
      'Dutch',
      'Filipino',
      'Finnish',
      'Swedish',
      'Greek',
      'Indonesian',
      'Hungarian',
      'Ukrainian',
      'ID',
      'Task Name',
      'Keyword Count',
      'Task Type',
      'Remarks',
      'Update Time',
      'Actions',
      'Keyword',
      'Task',
      'Remarks',
      'Update Time',
      'Actions',
    ],
    'zh-CN': [
      '关键词挖掘',
      '下拉关键词',
      '组合关键词',
      '相关搜索词',
      '大家都在搜',
      '竞对关键词',
      '关键词规划师',
      'AI挖掘词',
      '站长平台词',
      '关键词裂变',
      '关键词挖掘',
      '关键词组合',
      '挖掘平台',
      '挖掘深度',
      '高级筛选',
      '条件筛选',
      '组合方式',
      '智能加空格',
      '全选/全不选',
      '关键词去重',
      '特殊字符过滤',
      '保留原始词',
      '敏感词过滤',
      '字符长度',
      '最少',
      '最多',
      '结果包含',
      '结果不包含',
      '请输入需要挖掘的关键词，每行只输入一个关键词',
      '请选择自定义词库',
      '请选择最少字符数',
      '请选择最多字符数',
      '请输入关键词，每行一个关键词',
      '请输入竞争对手网址',
      '请选择关键词生成语言',
      '请输入AI提示词',
      '一行一个，请输入组合项',
      '请输入关键词，一行一个',
      '请输入竞争对手的官方网址，如：https://www.google.com，一行一个，一次最多提交5个竞对网站',
      '请输入需要提取关键词的竞争对手网址链接，一行一条url链接，需带https或http的网站链接地址',
      '请输入简体中文关键词，一行一个',
      '请输入需要挖掘关键词的产品或服务名称，一行一个，如：SEO公司',
      '请选择挖掘平台',
      '请选择挖掘深度',
      '请输入关键词',
      '关键词全部被过滤',
      '创建任务成功',
      '请输入关键词C',
      '请选择组合方式',
      '组合成功',
      '请先组合关键词',
      '复制成功',
      '复制失败',
      '请选择挖掘来源',
      '请选择搜索引擎',
      '请选择站长平台',
      'AI提示词中有且仅有{keyword}、{number}、{language}三个通配符',
      '请选择输出语言',
      '请选择排列顺序',
      '提交',
      '组合关键词',
      '组合项插入',
      '清空组合项',
      '挖掘关键词',
      'AI生成关键词',
      '一键插入AI提示词',
      '立即挖掘关键词',
      '1、一键拆分关键词',
      '2、提取所有词根',
      '3、同义词生成',
      '功能介绍',
      '使用说明',
      '下拉关键词，也叫联想词或下拉框关键词，它是根据你搜索框所输入的关键词所展现出来的你可能要搜索的相关词。',
      '若所有结果都被敏感词过滤或长度过滤，建议修改配置之后再进行挖掘。',
      'Kobetools关键词组合工具是一款秒级大批量支持多语言的高效文本组合工具，可灵活设置组合规则和过滤筛选条件，帮您为您生成想要的任何关键词。',
      '使用关键词组合工具核心词根(核心主要关键字)必须放在C区，输入的词或关键字必须一行一个，组合的关键词支持系统在线云端存储和本地TXT/Excel下载。',
      '相关搜索词工具，能够挖掘百度、谷歌等搜索引擎的相关搜索关键词，帮助您发现更多潜在的长尾关键词和用户搜索意图。',
      '大家都在搜关键词工具，能够挖掘百度、谷歌等搜索引擎的热搜关键词，帮助您快速了解用户关注的热点话题和搜索习惯。',
      'AI关键词生成工具是结合AI大数据模型，自动为您生成关键词，可根据市场调研、用户搜索行为分析等多种因素，快速生成高质量的关键词列表。',
      '支持自定义AI提示词，可根据您的需求灵活调整生成策略，为您的SEO优化、广告投放等提供强大支持。',
      '请输入关键词并设置裂变条件',
      '支持包含/不包含/长度/违禁词过滤',
      'AI提示词',
      '输出语言',
      '挖掘来源',
      '挖掘数量',
      '搜索引擎',
      '站长平台',
      '月搜索量',
      '搜索指数',
      '难度级别',
      '裂变数量',
      '排列顺序',
      '条件筛选',
      '标题字符长度',
      'A',
      'B',
      'C',
      'D',
      '前置',
      '中置',
      '后置',
      '组合项',
      '组合结果',
      '同语义裂变',
      '同义词裂变',
      '请帮我找出与{keyword}有关的{number}个关键词，关键词要满足用户商业搜索需求，要有一定的搜索热度，尽可能简短；关键词方向可以从价格、厂家、排行榜、推荐、费用、批发、热门地区、分类、使用场景等方向结合；只需要输入关键词，一行一个，不需要其他任何文本信息，输出{language}',
      '个',
      '谷歌',
      'SEO',
      '优化',
      '的',
      '技巧',
      '裂变配置',
      '任一项',
      '所有项',
      '任一项',
      '所有项',
      '一层',
      '二层',
      '三层',
      '四层',
      '五层',
      '去掉标点',
      '去掉空格',
      '公有词库',
      '自定义词库',
      '公有词库',
      '政治类',
      '公共词库别删',
      '公共正文过滤别删',
      '百度',
      '谷歌',
      '必应',
      '头条',
      '搜狗',
      '360',
      '百度',
      '谷歌',
      '必应',
      '头条',
      '360',
      '神马',
      '搜狗',
      '抖音',
      '小红书',
      '百度',
      '谷歌',
      '爱站工具',
      '站长工具',
      'SEMrush',
      'Ahrefs',
      '站长平台词',
      '竞价投放词',
      '站内SEO设置',
      '百度',
      '谷歌',
      '必应',
      '神马',
      '搜狗',
      '360',
      '无效关键词',
      '疑似品牌词',
      '联系方式词',
      '违禁敏感词',
      '知识科普词',
      '疑问解答词',
      '图片视频词',
      '低价值词',
      '手动录入',
      '智能清洗',
      '下拉关键词',
      '组合关键词',
      '相关搜索词',
      '大家都在搜',
      '竞对关键词',
      '关键词规划师',
      'AI挖掘词',
      '站长平台词',
      '原始词',
      '权重1',
      '权重2',
      '权重3',
      '新任务添加',
      '已有任务添加',
      'C (后置)',
      'AC',
      'BC',
      'CD',
      'BCD',
      'ABC',
      'ACD',
      'ABCD',
      '不限制',
      '2个',
      '3个',
      '4个',
      '5个',
      '默认顺序',
      '长短排列',
      '随机排列',
      '简体中文',
      '英文',
      '繁体中文',
      '俄语',
      '日语',
      '法语',
      '德语',
      '葡萄牙语',
      '阿拉伯语',
      '西班牙语',
      '意大利语',
      '越南语',
      '韩语',
      '印地语',
      '孟加拉语',
      '印尼语',
      '土耳其语',
      '泰语',
      '泰卢固语',
      '泰米尔语',
      '马来语',
      '捷克语',
      '荷兰语',
      '菲律宾语',
      '芬兰语',
      '瑞典语',
      '希腊语',
      '印度尼西亚语',
      '匈牙利语',
      '乌克兰语',
      'ID',
      '任务名称',
      '关键词数',
      '任务类型',
      '备注信息',
      '更新时间',
      '操作',
      '关键词',
      '所属任务',
      '备注信息',
      '更新时间',
      '操作',
    ],
    'zh-TW': [

      '關鍵詞挖掘',
      '下拉關鍵詞',
      '組合關鍵詞',
      '相關搜索詞',
      '大家都在搜',
      '競對關鍵詞',
      '關鍵詞規劃師',
      'AI挖掘詞',
      '站長平台詞',
      '關鍵詞裂變',
      '關鍵詞挖掘',
      '關鍵詞組合',
      '挖掘平台',
      '挖掘深度',
      '高級篩選',
      '條件篩選',
      '組合方式',
      '智能加空格',
      '全選/全不選',
      '關鍵詞去重',
      '特殊字符過濾',
      '保留原始詞',
      '敏感詞過濾',
      '字符長度',
      '最少',
      '最多',
      '結果包含',
      '結果不包含',
      '請輸入需要挖掘的關鍵詞，每行只輸入一個關鍵詞',
      '請選擇自定義詞庫',
      '請選擇最少字符数',
      '請選擇最多字符数',
      '請輸入關鍵詞，每行一個關鍵詞',
      '請輸入競爭對手网址',
      '請選擇關鍵詞生成語言',
      '請輸入AI提示詞',
      '一行一個，請輸入組合項',
      '請輸入關鍵詞，一行一個',
      '請輸入競爭對手的官方网址，如：https://www.google.com，一行一個，一次最多提交5個競對網站',
      '請輸入需要提取關鍵詞的競爭對手网址链接，一行一條url链接，需带https或http的網站链接地址',
      '請輸入簡體中文關鍵詞，一行一個',
      '請輸入需要挖掘關鍵詞的产品或服务名称，一行一個，如：SEO公司',
      '請選擇挖掘平台',
      '請選擇挖掘深度',
      '請輸入關鍵詞',
      '關鍵詞全部被過濾',
      '创建任務成功',
      '請輸入關鍵詞C',
      '請選擇組合方式',
      '組合成功',
      '請先組合關鍵詞',
      '複製成功',
      '複製失敗',
      '請選擇挖掘來源',
      '請選擇搜索引擎',
      '請選擇站長平台',
      'AI提示詞中有且僅有{keyword}、{number}、{language}三個通配符',
      '請選擇輸出語言',
      '請選擇排列順序',
      '提交',
      '組合關鍵詞',
      '組合項插入',
      '清空組合項',
      '挖掘關鍵詞',
      'AI生成關鍵詞',
      '一键插入AI提示詞',
      '立即挖掘關鍵詞',
      '1、一键拆分關鍵詞',
      '2、提取所有詞根',
      '3、同义詞生成',
      '功能介紹',
      '使用說明',
      '下拉關鍵詞，也叫联想詞或下拉框關鍵詞，它是根据你搜索框所輸入的關鍵詞所展现出来的你可能要搜索的相關詞。',
      '若所有結果都被敏感詞過濾或長度過濾，建议修改配置之后再進行挖掘。',
      'Kobetools關鍵詞組合工具是一款秒級大批量支持多語言的高效文本組合工具，可灵活設置組合規則和過濾篩選條件，帮您為您生成想要的任何關鍵詞。',
      '使用關鍵詞組合工具核心詞根(核心主要关键字)必须放在C區，輸入的詞或关键字必须一行一個，組合的關鍵詞支持系统在线云端存储和本地TXT/Excel下載。',
      '相關搜索詞工具，能够挖掘百度、谷歌等搜索引擎的相關搜索關鍵詞，帮助您发现更多潜在的長尾關鍵詞和用户搜索意圖。',
      '大家都在搜關鍵詞工具，能够挖掘百度、谷歌等搜索引擎的热搜關鍵詞，帮助您快速了解用户关注的热点话題和搜索习惯。',
      'AI關鍵詞生成工具是结合AI大數據模型，自动為您生成關鍵詞，可根据市场调研、用户搜索行為分析等多种因素，快速生成高质量的關鍵詞列表。',
      '支持自定義AI提示詞，可根据您的需求灵活调整生成策略，為您的SEO優化、广告投放等提供强大支持。',
      '請輸入關鍵詞并設置裂變條件',
      '支持包含/不包含/長度/違禁詞過濾',
      'AI提示詞',
      '輸出語言',
      '挖掘來源',
      '挖掘數量',
      '搜索引擎',
      '站長平台',
      '月搜索量',
      '搜索指数',
      '難度級別',
      '裂變數量',
      '排列順序',
      '條件篩選',
      '標題字符長度',
      'A',
      'B',
      'C',
      'D',
      '前置',
      '中置',
      '後置',
      '組合項',
      '組合結果',
      '同语义裂變',
      '同义詞裂變',
      '請帮我找出与{keyword}有关的{number}個關鍵詞，關鍵詞要滿足用户商業搜索需求，要有一定的搜索热度，尽可能簡短；關鍵詞方向可以從价格、厂家、排行榜、推荐、费用、批发、热门地區、分類、使用场景等方向结合；只需要輸入關鍵詞，一行一個，不需要其他任何文本信息，輸出{language}',
      '個',
      '谷歌',
      'SEO',
      '優化',
      '的',
      '技巧',
      '裂變配置',
      '任一項',
      '所有項',
      '任一項',
      '所有項',
      '一層',
      '二層',
      '三層',
      '四層',
      '五層',
      '去掉标点',
      '去掉空格',
      '公有詞庫',
      '自定義詞庫',
      '公有詞庫',
      '政治类',
      '公共詞庫別删',
      '公共正文過濾別删',
      '百度',
      '谷歌',
      '必應',
      '頭條',
      '搜狗',
      '360',
      '百度',
      '谷歌',
      '必應',
      '頭條',
      '360',
      '神马',
      '搜狗',
      '抖音',
      '小红书',
      '百度',
      '谷歌',
      '愛站工具',
      '站長工具',
      'SEMrush',
      'Ahrefs',
      '站長平台詞',
      '竞价投放詞',
      '站内SEO設置',
      '百度',
      '谷歌',
      '必應',
      '神马',
      '搜狗',
      '360',
      '無效關鍵詞',
      '疑似品牌詞',
      '聯系方式詞',
      '違禁敏感詞',
      '知識科普詞',
      '疑問解答詞',
      '圖片視頻詞',
      '低價值詞',
      '手動錄入',
      '智能清洗',
      '下拉關鍵詞',
      '組合關鍵詞',
      '相關搜索詞',
      '大家都在搜',
      '競對關鍵詞',
      '關鍵詞規劃師',
      'AI挖掘詞',
      '站長平台詞',
      '原始詞',
      '權重1',
      '權重2',
      '權重3',
      '新任務添加',
      '已有任務添加',
      'C (後置)',
      'AC',
      'BC',
      'CD',
      'BCD',
      'ABC',
      'ACD',
      'ABCD',
      '不限制',
      '2個',
      '3個',
      '4個',
      '5個',
      '默認順序',
      '長短排列',
      '隨機排列',
      '簡體中文',
      '英文',
      '繁體中文',
      '俄語',
      '日語',
      '法語',
      '德語',
      '葡萄牙語',
      '阿拉伯語',
      '西班牙語',
      '意大利語',
      '越南語',
      '韓語',
      '印地語',
      '孟加拉語',
      '印尼語',
      '土耳其語',
      '泰語',
      '泰盧固語',
      '泰米爾語',
      '馬來語',
      '捷克語',
      '荷蘭語',
      '菲律賓語',
      '芬蘭語',
      '瑞典語',
      '希臘語',
      '印度尼西亞語',
      '匈牙利語',
      '烏克蘭語',
      'ID',
      '任務名称',
      '關鍵詞数',
      '任務類型',
      '備注信息',
      '更新時間',
      '操作',
      '關鍵詞',
      '所属任務',
      '備注信息',
      '更新時間',
      '操作',
    ],
  },
};
