export default {
  field: [
    'pageName',
    'placeholder1',
    'placeholder2',
    'placeholder3',
    'placeholder4',
    'placeholder5',
    'placeholder6',
    'placeholder7',
    'button1',
    'button2',
    'button3',
    'button4',
    'button5',
    'button6',
    'button7',
    'button8',
    'button9',
    'button10',
    'title1',
    'title2',
    'title3',
    'title4',
    'label1',
    'label2',
    'label3',
    'label4',
    'label5',
    'label6',
    'message1',
    'message2',
    'message3',
    'message4',
    'message5',
    'content1',
    'content2',
    'status.paused',
    'status.generating',
    'taskTableColumns.title5',
    'includeOptions.label1',
    'includeOptions.label2',
    'excludeOptions.label1',
    'excludeOptions.label2',
    'lengthOptions.unlimited',
    'GLEngineOptions.label1',
    'GLEngineOptions.label2',
    'GLEngineOptions.label3',
    'GLEngineOptions.label4',
    'GLEngineOptions.label5',
    'GLEngineOptions.label6',
    'GLEngineOptions.label7',
    'GLEngineOptions.label8',
  ],
  value: {
    'en-US': [
      'Keyword Tasks',
      'Task Type',
      'Please select custom word library',
      'Please select minimum character count',
      'Please select maximum character count',
      'Please enter keywords, one per line',
      'Enter task name keyword',
      'Enter remark keyword',
      'Search',
      'Reset',
      'Refresh',
      'Details',
      'Clean',
      'Pause',
      'Delete',
      'Save',
      'Cancel',
      'Confirm',
      'Clean Task: ',
      'Filter Settings',
      'Include/Exclude',
      'AI Filter',
      'Character Length',
      'Sensitive Word Filter',
      'Minimum',
      'Maximum',
      'Results Include',
      'Results Exclude',
      'No data has been modified',
      'Saved successfully',
      'Cleaned successfully',
      'Paused successfully',
      'Deleted successfully',
      'Pause this task?',
      'Delete this task?',
      'Paused',
      'Generating',
      'Remarks',
      'Any one',
      'All',
      'Any one',
      'All',
      'Unlimited',
      'Invalid Keywords',
      'Brand Keywords',
      'Contact Information',
      'Sensitive Words',
      'Knowledge & Education',
      'Q&A Keywords',
      'Image & Video Keywords',
      'Low Value Keywords',
    ],
    'zh-CN': [
      '关键词任务',
      '任务类型',
      '请选择自定义词库',
      '请选择最少字符数',
      '请选择最多字符数',
      '请输入关键词，每行一个关键词',
      '输入任务名称关键字',
      '输入备注信息关键字',
      '搜索',
      '重置',
      '刷新',
      '详情',
      '清洗',
      '暂停',
      '删除',
      '保存',
      '取消',
      '确定',
      '清洗任务：',
      '过滤设置',
      '包含不包含',
      'AI过滤',
      '字符长度',
      '违禁词过滤',
      '最少',
      '最多',
      '结果包含',
      '结果不包含',
      '您暂未修改数据',
      '保存成功',
      '清洗成功',
      '暂停成功',
      '删除成功',
      '是否暂停当前任务？',
      '是否删除当前任务？',
      '暂停中',
      '生成中',
      '备注信息',
      '任一项',
      '所有项',
      '任一项',
      '所有项',
      '不限制',
      '无效关键词',
      '疑似品牌词',
      '联系方式词',
      '违禁敏感词',
      '知识科普词',
      '疑问解答词',
      '图片视频词',
      '低价值词',
    ],
    'zh-TW': [

      '關鍵詞任務',
      '任務類型',
      '請選擇自定義詞庫',
      '請選擇最少字符数',
      '請選擇最多字符数',
      '請輸入關鍵詞，每行一個關鍵詞',
      '輸入任務名称关键字',
      '輸入備注信息关键字',
      '搜索',
      '重置',
      '刷新',
      '詳情',
      '清洗',
      '暫停',
      '刪除',
      '保存',
      '取消',
      '確定',
      '清洗任務：',
      '過濾設置',
      '包含不包含',
      'AI過濾',
      '字符長度',
      '違禁詞過濾',
      '最少',
      '最多',
      '結果包含',
      '結果不包含',
      '您暫未修改數據',
      '保存成功',
      '清洗成功',
      '暫停成功',
      '刪除成功',
      '是否暫停當前任務？',
      '是否刪除當前任務？',
      '暫停中',
      '生成中',
      '備注信息',
      '任一項',
      '所有項',
      '任一項',
      '所有項',
      '不限制',
      '無效關鍵詞',
      '疑似品牌詞',
      '聯系方式詞',
      '違禁敏感詞',
      '知識科普詞',
      '疑問解答詞',
      '圖片視頻詞',
      '低價值詞',
    ],
  },
};

