export default {
  'placeholder1': '请输入分组名称',
  'btn1': '添加图片分组',
  'btn2': '刷新',
  'btn3': '查看图片',
  'btn4': '编辑',
  'btn5': '删除',
  'btn6': '取消',
  'btn7': '确定',
  'message1': '是否确认删除？',
  'message2': '请输入图片分组名称',
  'message3': '修改成功',
  'message4': '添加成功',
  'message5': '删除成功',
  'title1': '添加图片分组',
  'label1': '分组名称',
  'storageTableColumns.title1': 'ID',
  'storageTableColumns.title2': '名称',
  'storageTableColumns.title3': '更新时间',
  'storageTableColumns.title4': '操作',
};
