export default {
  'pageName': '网站TDK查询',
  'type1': '网站TDK查询',
  'type2': '链接TDK查询',
  'placeholder1': '请输入需要查询的网站域名，一行一个，单词最多提交10个，格式如：www.google.com',
  'button1': '立即查询',
  'button2': '导出查询结果',
  'button3': 'VIP查询通道',
  'message1': '请输入需要查询的网站域名！',
  'message2': '未获取到查询结果',
  'introduce1': '工具介绍：',
  'content1': '1、Kobetools网站TDK查询工具支持批量查询网站的标题(Title)、描述(Description)、关键词(Keywords)信息。',
  'content2': '2、Kobetools网站TDK查询工具可以快速分析竞争对手站点的TDK设置和SEO策略。',
  'columns.label1': '序号',
  'columns.label2': '网站域名',
  'columns.label3': '网站标题',
  'columns.label4': '网站关键词',
  'columns.label5': '网站描述',
  'linkColumns.label1': '序号',
  'linkColumns.label2': '链接地址',
  'linkColumns.label3': '网站标题',
  'linkColumns.label4': '网站关键词',
  'linkColumns.label5': '网站描述',
};

