export default {
  'placeholder1': '请输入CMS授权码',
  'placeholder2': '请输入授权站点',
  'btn1': '添加CMS',
  'btn2': '删除',
  'btn3': '取消',
  'btn4': '确定',
  'message1': '是否删除当前CMS？',
  'message2': '请输入CMS授权码',
  'message3': '请输入授权站点',
  'message4': '添加成功',
  'message5': '删除成功',
  'title1': '添加CMS',
  'label1': '选择CMS',
  'label2': 'CMS授权码',
  'label3': '授权站点',
  'cmsOptions.label1': '卓商站宝',
  'tableColumns.title1': 'CMS站点',
  'tableColumns.title2': '站点名称',
  'tableColumns.title3': '站点域名',
  'tableColumns.title4': '操作',
};
