export default {
  'placeholder1': '请输入账号名称',
  'placeholder2': '请输入密钥KEY',
  'btn1': '添加AI',
  'btn2': '删除',
  'btn3': '取消',
  'btn4': '确定',
  'message1': '是否确认删除？',
  'message2': '请输入账号名称',
  'message3': '请输入密钥KEY',
  'message4': '添加成功',
  'message5': '删除成功',
  'title1': '添加AI',
  'label1': '选择AI类型',
  'label2': '账号名称',
  'label3': '密钥KEY',
  'AIOptions.label1': 'ChatGPT',
  'otherConfigTableColumns.title1': 'AI类型',
  'otherConfigTableColumns.title2': '账号名称',
  'otherConfigTableColumns.title3': 'KEY',
  'otherConfigTableColumns.title4': '操作',
};
