export default {
  field: [
    'pageName', 'type1', 'placeholder1', 'placeholder2', 'placeholder3',
    'button1', 'button2', 'button3', 'message1',
    'label1', 'label2', 'label3', 'label4',
    'portOptions.pc', 'portOptions.wap',
    'queryModeOptions.fast', 'queryModeOptions.realtime',
    'locationOptions.china',
    'introduce1', 'content1', 'content2',
    'columns.label1', 'columns.label2', 'columns.label3', 'columns.label4',
    'columns.label5', 'columns.label6', 'columns.label7', 'columns.label8', 'columns.label9',
    'searchEngines.baidu', 'searchEngines.google', 'searchEngines.bing',
    'searchEngines.so', 'searchEngines.sogou', 'searchEngines.sm',
    'searchEngines.toutiao', 'searchEngines.yahu', 'searchEngines.yandex',
  ],
  value: {
    'en-US': [
      'Keywords Ranking Query', 'Keywords Ranking Query',
      'Enter domains to query, one per line, max 10 per submission, format: google.com',
      'Select Country', 'Select City',
      'Query Now', 'Export to Local', 'VIP Query Channel', 'Please enter domain information!',
      'Search Engine', 'Port Selection', 'Query Mode', 'Location Selection',
      'PC', 'WAP', 'Fast Query', 'Real-time Query', 'China',
      'Tool Introduction:',
      '1. Kobetools search engine ranking query tool supports efficient, large-scale querying of keyword rankings across major search engines, with precise location targeting by country and city for real-time ranking queries.',
      '2. Kobetools search engine ranking query tool also supports range-specific ranking queries, including single site queries, multi-site mixed queries, and local document upload queries.',
      'No.', 'Website Domain', 'Keyword', 'Search Engine', 'Ranking', 'Port', 'Status', 'Region Node', 'Action',
      'Baidu', 'Google', 'Bing', '360', 'Sogou', 'Shenma', 'Toutiao', 'Yahoo', 'Yandex',
    ],
    'zh-CN': [
      '关键词排名查询', '关键词排名查询',
      '请输入需要查询的域名信息，一行一个，单次最多提交10个，格式如：google.com',
      '选择国家', '选择城市',
      '立即查询', '导出到本地', 'VIP查询通道', '请输入需要查询的域名信息！',
      '搜索引擎', '端口选择', '查询模式', '位置选择',
      'PC', 'WAP', '快速查询', '实时查询', '中国',
      '工具介绍：',
      '1、Kobetools搜索引擎排名查询工具支持高效率、大批量查询各大搜索引擎关键词排名，可精准定位国家及城市节点查询实时排名。',
      '2、Kobetools搜索引擎排名查询工具还可以指定范围查询排名，支持单个站点查询、多站点混合查询以及本地文档上传查询。',
      '序号', '网站域名', '关键词', '搜索引擎', '排名', '端口', '状态', '地区节点', '操作',
      '百度', '谷歌', '必应', '360', '搜狗', '神马', '头条', '雅虎', 'Yandex',
    ],
    'zh-TW': [
      '關鍵詞排名查詢', '關鍵詞排名查詢',
      '請輸入需要查詢的域名信息，一行一個，單次最多提交10個，格式如：google.com',
      '選擇國家', '選擇城市',
      '立即查詢', '導出到本地', 'VIP查詢通道', '請輸入需要查詢的域名信息！',
      '搜索引擎', '端口選擇', '查詢模式', '位置選擇',
      'PC', 'WAP', '快速查詢', '實時查詢', '中國',
      '工具介紹：',
      '1、Kobetools搜索引擎排名查詢工具支持高效率、大批量查詢各大搜索引擎關鍵詞排名，可精準定位國家及城市節點查詢實時排名。',
      '2、Kobetools搜索引擎排名查詢工具還可以指定範圍查詢排名，支持单個站點查詢、多站點混合查詢以及本地文檔上傳查詢。',
      '序號', '網站域名', '關鍵詞', '搜索引擎', '排名', '端口', '狀態', '地區節點', '操作',
      '百度', '谷歌', '必應', '360', '搜狗', '神馬', '頭條', '雅虎', 'Yandex',
    ],
  },
};

