export default {
  'placeholder1': '输入词库名称',
  'placeholder2': '选择词库类型',
  'btn1': '搜索',
  'btn2': '重置',
  'btn3': '刷新',
  'btn4': '导出',
  'message1': '是否导出当前分组的所有词？',
  'message2': '您暂未修改数据',
  'message3': '保存成功',
  'typeOptions.label1': '敏感违禁词',
  'typeOptions.label2': '同义近义词',
  'groupTableColumns.title1': 'ID',
  'groupTableColumns.title2': '词库类型',
  'groupTableColumns.title3': '分组名称',
  'groupTableColumns.title4': '词库数量',
  'groupTableColumns.title5': '更新时间',
  'groupTableColumns.title6': '操作',
};
